#!/bin/sh

if [ x"$1" = x"sh" -o x"$1" = x"bash" ]; then
  exec $@
  exit
fi

[ ! -e /elasticsearch/config/elasticsearch.yml ] \
  && echo "Generating configs" \
  && cp -R /elasticsearch/config.orig/* /elasticsearch/config/ \
  && chown -R elasticsearch:elasticsearch /elasticsearch/config

chown -R elasticsearch:elasticsearch /elasticsearch/data
chown -R elasticsearch:elasticsearch /elasticsearch/logs

exec su elasticsearch -c "elasticsearch/bin/elasticsearch $@"
